#!/usr/bin/env bash
# This script configures an Ubuntu server with custom DNS settings

# Check if script is run with sudo
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root"
    exit 1
fi

# Set custom DNS settings
echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

# Apply changes
systemctl restart systemd-resolved.service

